---
- name: Install common packages
  apt:
    state: present
    pkg: 
      - apt-transport-https
      - auditd
      - bzip2
      - chkrootkit
      - clamav
      - curl
      - fping
      - htop
      - lnav
      - lynis
      - multitail
      - netdiscover
      - python3-apt
      - rkhunter
      - rng-tools
      - sudo
      - tcpdump
      - tree
      - tzdata
      - unattended-upgrades
      - vim
      - wget
  tags: [base]

- name: Set timezone to Europe/Paris
  timezone:
    name: Europe/Paris
  tags: [base]
